dist: trusty

language: node_js

node_js:
    - "12"
    - "14"

before_script:
    - npm install

script:
    - npm run lint
    - npm run prettier
    - npm test
    - npm run build

after_script:
    - npm install -g codecov
    - codecov
